# bugs.python.
     or http://127.0.0.1:8888/?token=b436a7475e9fa9883f74fb235bffa44e2d2996ca07a3fc43 This version of python seems to be incorrectly compiled (internal generated filenames are not absolute). This may make the debugger miss breakpoints. Related bug: http://bugs.python.org/issue1666807
